TwilioChat/TwilioChat/Models/Channel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TwilioChat.Models
{
    public class Channel
    {
        public string sid { get; set; }
        public string account_sid { get; set; }
        public string service_sid { get; set; }
        public string friendly_name { get; set; }
        public string unique_name { get; set; }
        public string type { get; set; }
        public DateTime date_created { get; set; }
        public DateTime date_updated { get; set; }
        public string created_by { get; set; }
        public int members_count { get; set; }
        public int messages_count { get; set; }
        public string url { get; set; }
    }
}

TwilioChat/TwilioChat/Controllers/AdministratorController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Web;
using System.Web.Mvc;
using Twilio;
using Twilio.Rest.Chat.V2;
using Twilio.Rest.Chat.V2.Service;
using Twilio.Rest.Chat.V2.Service.Channel;
using Twilio.Rest.Chat.V2.Service.User;
using TwilioChat.Models;

namespace TwilioChat.Controllers
{
    public class AdministratorController : Controller
    {
        public ViewResult view;
        public ActionResult Index()
        {
            view = View();
            return View();

        }

        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            string name = Convert.ToString(collection["username"]);
            TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
            var users = Twilio.Rest.Chat.V2.Service.UserResource.Read(
                pathServiceSid: GlobalVariables.pathServiceSid
            );

            List<string> listUsers = new List<string>();
            TwilioChat.Models.User user = new TwilioChat.Models.User();
            foreach (var record in users)
            {
                listUsers.Add(record.Identity);
            }
            if (listUsers.Count.Equals(0))
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            else
            {
                if (listUsers.Contains(name))
                    return RedirectToAction("Channels");
            }
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }

        [HttpGet]
        public ActionResult Channels()
        {
            TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
            var channels = ChannelResource.Read(pathServiceSid: GlobalVariables.pathServiceSid);
            Channel channelList = new Channel();
            List<Channel> list = new List<Channel>();
            foreach (var item in channels)
            {
                channelList = new Channel
                {
                    sid = String.IsNullOrEmpty(item.Sid) ? "" : item.Sid.ToString(),
                    account_sid = String.IsNullOrEmpty(item.AccountSid) ? "" : item.AccountSid.ToString(),
                    service_sid = String.IsNullOrEmpty(item.ServiceSid) ? "" : item.ServiceSid.ToString(),
                    friendly_name = String.IsNullOrEmpty(item.FriendlyName) ? "" : item.FriendlyName.ToString(),
                    unique_name = String.IsNullOrEmpty(item.UniqueName) ? "" : item.UniqueName.ToString()
                };
                list.Add(channelList);
            }
            string json = JsonConvert.SerializeObject(list);
            var listado = JsonConvert.DeserializeObject<List<Channel>>(json.ToString());
            return View(listado);
        }
        //
        [HttpGet]
        public ActionResult NewChannel()
        {
            return View();
        }
        //
        [HttpPost]
        public ActionResult NewChannel(Channel channel)
        {
            TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
            var channels = ChannelResource.Create(pathServiceSid: GlobalVariables.pathServiceSid,
                friendlyName: channel.friendly_name, uniqueName: channel.unique_name);
            if (!channels.Sid.Equals(""))
            {
                return RedirectToAction("Channels");
            }
            return View();
        }
        //
        [HttpGet]
        public ActionResult UpdateChannel(string sid)
        {
            try
            {
                TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
                var channels = ChannelResource.Read(pathServiceSid: GlobalVariables.pathServiceSid);
                Channel ochannel = new Channel();
                List<Channel> list = new List<Channel>();
                foreach (var item in channels)
                {
                    if (item.Sid.Equals(sid))
                    {
                        Channel channel = new Channel
                        {
                            sid = String.IsNullOrEmpty(item.Sid) ? "" : item.Sid.ToString(),
                            account_sid = String.IsNullOrEmpty(item.AccountSid) ? "" : item.AccountSid.ToString(),
                            service_sid = String.IsNullOrEmpty(item.ServiceSid) ? "" : item.ServiceSid.ToString(),
                            friendly_name = String.IsNullOrEmpty(item.FriendlyName) ? "" : item.FriendlyName.ToString(),
                            unique_name = String.IsNullOrEmpty(item.UniqueName) ? "" : item.UniqueName.ToString()
                        };
                        ochannel = channel;
                        break;
                    }
                }
                return View(ochannel);
            }
            catch (Exception)
            {
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            }
        }

        [HttpPost]
        public ActionResult UpdateChannel(Channel channel)
        {
            TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
            
            var result = ChannelResource.Update(
                friendlyName: channel.friendly_name,
                uniqueName: channel.unique_name,
                pathServiceSid: GlobalVariables.pathServiceSid,
                pathSid: channel.sid

            );
            if (!result.Sid.Equals(""))
            {
                return RedirectToAction("Channels");
            }
            return View();
        }

        [HttpGet]
        public ActionResult DeleteChannel(string sid)
        {
            TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
            ChannelResource.Delete(
                pathServiceSid: GlobalVariables.pathServiceSid,
                pathSid: sid
            );
            return RedirectToAction("Channels");
        }
    }
}

TwilioChat/TwilioChat/Controllers/ChannelController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using Twilio;
using Twilio.Rest.Chat.V2;
using Twilio.Rest.Chat.V2.Service;
using Twilio.Rest.Chat.V2.Service.Channel;
using Twilio.Rest.Chat.V2.Service.User;
using TwilioChat.Models;


namespace TwilioChat.Controllers
{
    public class ChannelController : Controller
    {
        public ActionResult Index()
        {
            TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
            var channels = ChannelResource.Read(GlobalVariables.pathServiceSid);
            Channel channel = new Channel();
            List<Channel> list = new List<Channel>();
            foreach (var item in channels)
            {
                channel.sid = String.IsNullOrEmpty(item.Sid) ? "" : item.Sid.ToString();
                channel.account_sid = String.IsNullOrEmpty(item.AccountSid) ? "" : item.AccountSid.ToString(); 
                channel.service_sid = String.IsNullOrEmpty(item.ServiceSid) ? "" : item.ServiceSid.ToString();
                channel.friendly_name = String.IsNullOrEmpty(item.FriendlyName) ? "" : item.FriendlyName.ToString();  
                channel.unique_name = String.IsNullOrEmpty(item.UniqueName) ? "" : item.UniqueName.ToString();
                list.Add(channel);
            }
            string json = JsonConvert.SerializeObject(list);
            var listado = JsonConvert.DeserializeObject<List<Channel>>(json.ToString());
            return View(listado);
        }
    }
}

TwilioChat/TwilioChat/Views/Administrator/Channels.cshtml
@{
    ViewBag.Title = "Channels";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    html, body {
        height: 100%;
        width: 100%;
        padding: 0;
        margin: 0;
        background-image: none;
        background-color: white;
    }
</style>
<br />
<a href="@Url.Action("NewChannel", "Administrator")" class="btn btn-primary right">New Channel</a>
<br />
<h2>List Channels</h2>
<hr />
<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">SID</th>
            <th scope="col">FRIENDLY NAME</th>
            <th scope="col">UNIQUE NAME</th>
            <th scope="col">ACTIONS</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var channel in Model)
        {
            <tr>
                <th scope="row">@channel.sid</th>
                <th>@channel.friendly_name</th>
                <th>@channel.unique_name</th>
                <th>
                    <a href="@Url.Action("UpdateChannel", "Administrator", new { sid = channel.sid})" class="btn btn-success right">Update</a>
                    <a href="@Url.Action("DeleteChannel", "Administrator", new { sid = channel.sid})" class="btn btn-danger right">Delete</a>
                </th>
            </tr>
        }
    </tbody>
</table>

TwilioChat/TwilioChat/Views/Administrator/Index.cshtml
@{
    ViewBag.Title = "Administrator";
}
<style>
    body {
        background-image: url('http://getwallpapers.com/wallpaper/full/a/5/d/544750.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        height: 100%;
        font-family: 'Numans', sans-serif;
    }

    footer p {
        color: white;
    }

    .admin {
        margin-top: 60px;
    }

    .card {
        height: 220px;
        margin-top: auto;
        margin-bottom: auto;
        width: 400px;
        background-color: rgba(0,0,0,0.5) !important;
    }

    .social_icon span {
        font-size: 60px;
        margin-left: 10px;
        color: #FFC312;
    }

    .social_icon span:hover {
        color: white;
        cursor: pointer;
    }

    .card-header h3 {
        color: white;
    }

    .social_icon {
        position: absolute;
        right: 20px;
        top: -45px;
    }

    .input-group-prepend span {
        width: 50px;
        background-color: #FFC312;
        color: black;
        border: 0 !important;
    }

    input:focus {
        outline: 0 0 0 0 !important;
        box-shadow: 0 0 0 0 !important;
    }

    .remember {
        color: white;
    }

    .remember input {
        width: 20px;
        height: 20px;
        margin-left: 15px;
        margin-right: 5px;
    }

    .login_btn {
        color: black;
        background-color: #FFC312;
        width: 100px;
        
    }

    .login_btn:hover {
        color: black;
        background-color: white;
    }

    .links {
        color: white;
    }

    .links a {
        margin-left: 4px;
    }

</style>

<br />

<div class="admin d-flex justify-content-center h-100">
    <div class="card">
        <div class="card-header">
            <h3>Sign In</h3>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Login", "Administrator", FormMethod.Post))
            {
                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" id="username" name="username" class="form-control" placeholder="username">
                </div>
                <div class="form-group" style="padding-right: 30px;">
                    <input type="submit" class="btn float-right login_btn" value="Enter" />
                </div>
            }
        </div>
    </div>
</div>

TwilioChat/TwilioChat/Views/Administrator/NewChannel.cshtml
@model TwilioChat.Models.Channel
@{
    ViewBag.Title = "CreateChannel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    html, body {
        height: 100%;
        width: 100%;
        padding: 0;
        margin: 0;
        background-image: none;
        background-color: white;
    }
</style>
<br />
<h2>New Channel</h2>
<hr />
<form method="post" action="@Url.Action("NewChannel", "Administrator")">
    <div class="form-group">
        <label>Channel Id</label>
        @Html.TextBoxFor(x => x.sid, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div class="form-group">
        <label>Friendly Name</label>
        @Html.TextBoxFor(x => x.friendly_name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Unique Name</label>
        @Html.TextBoxFor(x => x.unique_name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-success" value="Send" />
        <a href="@Url.Action("Channels", "Administrator")" class="btn btn-danger right">Back</a>
    </div>
</form>

TwilioChat/TwilioChat/Views/Administrator/UpdateChannel.cshtml
@model TwilioChat.Models.Channel
@{
    ViewBag.Title = "UpdateChannel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    html, body {
        height: 100%;
        width: 100%;
        padding: 0;
        margin: 0;
        background-image: none;
        background-color: white;
    }
</style>
<br />
<h2>UpdateChannel</h2>
<hr />
<form method="post" action="@Url.Action("UpdateChannel", "Administrator")">
    @using (Html.BeginForm())
    {
        <div class="form-group">
            <label>Channel Id</label>
            @Html.TextBoxFor(x => x.sid, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="form-group">
            <label>Friendly Name</label>
            @Html.TextBoxFor(x => x.friendly_name, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Unique Name</label>
            @Html.TextBoxFor(x => x.unique_name, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Send" />
            <a href="@Url.Action("Channels", "Administrator")" class="btn btn-danger right">Back</a>
        </div>
    }

</form>