WebApi/ClienteWebStudent/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClienteWebStudent.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApi/ClienteWebStudent/Controllers/StudentController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using ClienteWebStudentB;
using System.Net.Http.Formatting;

namespace ClienteWebStudent.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            HttpClient studentClientHttp = new HttpClient();
            studentClientHttp.BaseAddress = new Uri("http://localhost:2135/");
            var request = studentClientHttp.GetAsync("api/Student").Result;
            if (request.IsSuccessStatusCode)//200
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var listado = JsonConvert.DeserializeObject<List<Student>>(resultString);
                return View(listado);
            }
            return View(new List<Student>());
        }

        [HttpGet]
        public ActionResult NewStudent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewStudent(Student student)
        {
            HttpClient studentClientHttp = new HttpClient();
            studentClientHttp.BaseAddress = new Uri("http://localhost:2135/");
            var request = studentClientHttp.PostAsync("api/Student", student, new JsonMediaTypeFormatter()).Result;
            if (request.IsSuccessStatusCode)//200
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var resultado = JsonConvert.DeserializeObject<bool>(resultString);
                if (resultado)
                {
                    return RedirectToAction("Index");
                }
                return View(student);
            }
            return View(student);
        }

        [HttpGet]
        public ActionResult UpdateStudent(int studentID)
        {
            HttpClient studentClientHttp = new HttpClient();
            studentClientHttp.BaseAddress = new Uri("http://localhost:2135/");
            var request = studentClientHttp.GetAsync("api/Student?studentID=" + studentID).Result;
            if (request.IsSuccessStatusCode)//200
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var info = JsonConvert.DeserializeObject<Student>(resultString);
                return View(info);
            }
            return View();
        }

        [HttpPost]
        public ActionResult UpdateStudent(Student student)
        {
            HttpClient studentClientHttp = new HttpClient();
            studentClientHttp.BaseAddress = new Uri("http://localhost:2135/");
            var request = studentClientHttp.PutAsync("api/Student", student, new JsonMediaTypeFormatter()).Result;
            if (request.IsSuccessStatusCode)//200
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var resultado = JsonConvert.DeserializeObject<bool>(resultString);
                if (resultado)
                {
                    return RedirectToAction("Index");
                }
                return View(student);
            }
            return View(student);
        }

        [HttpGet]
        public ActionResult DeleteStudent(int studentID)
        {
            HttpClient studentClientHttp = new HttpClient();
            studentClientHttp.BaseAddress = new Uri("http://localhost:2135/");
            var request = studentClientHttp.DeleteAsync("api/Student?studentID=" + studentID).Result;
            if (request.IsSuccessStatusCode)//200
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var resultado = JsonConvert.DeserializeObject<bool>(resultString);
                if (resultado)
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult DetailStudent(int studentID)
        {
            HttpClient studentClientHttp = new HttpClient();
            studentClientHttp.BaseAddress = new Uri("http://localhost:2135/");
            var request = studentClientHttp.GetAsync("api/Student?studentID=" + studentID).Result;
            if (request.IsSuccessStatusCode)//200
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var info = JsonConvert.DeserializeObject<Student>(resultString);
                return View(info);
            }
            return View();
        }
    }
}

WebApi/ClienteWebStudent/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApi/ClienteWebStudent/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApi/ClienteWebStudent/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApi/ClienteWebStudent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApi/ClienteWebStudent/Views/Student/DetailStudent.cshtml
@model Student
@{
    ViewBag.Title = "Student Details";
}

<h2>Student Details</h2>
<hr />

<div class="form-group">
    <label>Student Id: </label>
    @Model.studentID
</div>
<div class="form-group">
    <label>FirstName: </label>
    @Model.firstname
</div>
<div class="form-group">
    <label>LastName: </label>
    @Model.lastname
</div>
<div class="form-group">
    <label>Email: </label>
    @Model.email
</div>
<div class="form-group">
    <label>Address: </label>
    @Model.address
</div>
<div class="form-group">
    <a href="@Url.Action("Index", "Student")" class="btn btn-danger right">Back</a>
</div>

WebApi/ClienteWebStudent/Views/Student/Index.cshtml
@model List<Student>
@{
    ViewBag.Title = "Index";
}
<h2>
    <a href="@Url.Action("NewStudent", "Student")" class="btn btn-primary right">New Student</a>
    List Students</h2>
<hr/>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Id</td>
            <td>FirstName</td>
            <td>LastName</td>
            <td>Email</td>
            <td>Address</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>@student.studentID</td>
                <td>@student.firstname</td>
                <td>@student.lastname</td>
                <td>@student.email</td>
                <td>@student.address</td>
                <td>
                    <a href="@Url.Action("UpdateStudent", "Student", new { studentID = student.studentID})" class="btn btn-success right">Update</a>
                    <a href="@Url.Action("DeleteStudent", "Student", new { studentID = student.studentID})" class="btn btn-danger right">Delete</a>
                    <a href="@Url.Action("DetailStudent", "Student", new { studentID = student.studentID})" class="btn btn-default right">Seee Detail</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApi/ClienteWebStudent/Views/Student/NewStudent.cshtml
@model Student
@{
    ViewBag.Title = "New Student";
}

<h2>New Student</h2>
<hr />
<form method="post" action="@Url.Action("NewStudent", "Student")">
    <div class="form-group">
        <label>Student Id</label>
        @Html.TextBoxFor(x=>x.studentID, new { @class= "form-control",  @readonly = "readonly" })
    </div>
    <div class="form-group">
        <label>Firsname</label>
        @Html.TextBoxFor(x => x.firstname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>LastName</label>
        @Html.TextBoxFor(x => x.lastname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Email</label>
        @Html.TextBoxFor(x => x.email, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Address</label>
        @Html.TextBoxFor(x => x.address, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-success" value="Send"/>
        <a href="@Url.Action("Index", "Student")" class="btn btn-danger right">Back</a>
    </div>
</form>

WebApi/ClienteWebStudent/Views/Student/UpdateStudent.cshtml
@model Student
@{
    ViewBag.Title = "Update Student";
}

<h2>Update Student</h2>
<hr />
<form method="post" action="@Url.Action("UpdateStudent", "Student")">
    <div class="form-group">
        <label>Student Id</label>
        @Html.TextBoxFor(x => x.studentID, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div class="form-group">
        <label>Firsname</label>
        @Html.TextBoxFor(x => x.firstname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>LastName</label>
        @Html.TextBoxFor(x => x.lastname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Email</label>
        @Html.TextBoxFor(x => x.email, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Address</label>
        @Html.TextBoxFor(x => x.address, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-success" value="Send" />
        <a href="@Url.Action("Index", "Student")" class="btn btn-danger right">Back</a>
    </div>
</form>