TwilioChat/TwilioChat/Controllers/ChatController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Web;
using System.Web.Mvc;
using Twilio;
using Twilio.Rest.Chat.V2;
using Twilio.Rest.Chat.V2.Service;
using Twilio.Rest.Chat.V2.Service.Channel;
using Twilio.Rest.Chat.V2.Service.User;
using TwilioChat.Models;

namespace TwilioChat.Controllers
{
    public class ChatController : Controller
    {
        public static string identity = "";
        public ActionResult Index()
        {
            TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
            var channels = ChannelResource.Read(GlobalVariables.pathServiceSid);
            Channel channel = new Channel();
            List<Channel> list = new List<Channel>();
            foreach (var item in channels)
            {
                channel = new Channel();
                channel.sid = String.IsNullOrEmpty(item.Sid) ? "" : item.Sid.ToString();
                channel.account_sid = String.IsNullOrEmpty(item.AccountSid) ? "" : item.AccountSid.ToString();
                channel.service_sid = String.IsNullOrEmpty(item.ServiceSid) ? "" : item.ServiceSid.ToString();
                channel.friendly_name = String.IsNullOrEmpty(item.FriendlyName) ? "" : item.FriendlyName.ToString();
                channel.unique_name = String.IsNullOrEmpty(item.UniqueName) ? "" : item.UniqueName.ToString();
                list.Add(channel);
            }
            string json = JsonConvert.SerializeObject(list);
            var listado = JsonConvert.DeserializeObject<List<Channel>>(json.ToString());
            return View(listado);
        }

        [HttpPost]
        public ActionResult ChatRoom(FormCollection collection)
        {
            string name = Convert.ToString(collection["nickname"]);
            string channel = Convert.ToString(collection["radioChannel"]);
            if (name.Equals(""))
            {
                GlobalVariables.pathChannelSid = channel;
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            }
            if (channel.Equals(""))
            {
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            }
            TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
            var members = Twilio.Rest.Chat.V2.Service.Channel.MemberResource.Read(
                pathServiceSid: GlobalVariables.pathServiceSid,
                pathChannelSid: channel
            );
            //VERIFICAR SI EL NICKNAME YA PERTENECE A LOS USUARIOS DEL CANAL
            foreach (var record in members)
            {
                if (name.Equals(record.Identity) && channel.Equals(record.ChannelSid))
                {
                    GlobalVariables.GetUserName = name;
                    GlobalVariables.pathChannelSid = channel;
                    return RedirectToAction("ChatRoom");
                }
            }
            //CREACION DE MEMBER
            var member = Twilio.Rest.Chat.V2.Service.Channel.MemberResource.Create(
                identity: name,
                pathServiceSid: GlobalVariables.pathServiceSid,
                pathChannelSid: channel
            );
            if (member.Sid.Equals(""))
            {
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            }
            GlobalVariables.GetUserName = name;
            GlobalVariables.pathChannelSid = channel;
            return RedirectToAction("ChatRoom");
        }

        [HttpGet]
        public ActionResult ChatRoom()
        {
            try
            {
                TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
                var members = Twilio.Rest.Chat.V2.Service.Channel.MemberResource.Read(GlobalVariables.pathServiceSid, GlobalVariables.pathChannelSid);
                Member member = new Member();
                List<Member> listMember = new List<Member>();
                foreach (var item in members)
                {
                    member = new Member();
                    member.sid = String.IsNullOrEmpty(item.Sid) ? "" : item.Sid.ToString();
                    member.account_sid = String.IsNullOrEmpty(item.AccountSid) ? "" : item.AccountSid.ToString();
                    member.service_sid = String.IsNullOrEmpty(item.ServiceSid) ? "" : item.ServiceSid.ToString();
                    member.channel_sid = String.IsNullOrEmpty(item.ChannelSid) ? "" : item.ChannelSid.ToString();
                    member.identity = String.IsNullOrEmpty(item.Identity) ? "" : item.Identity.ToString();
                    listMember.Add(member);
                }
                //

                TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);
                var mess = Twilio.Rest.Chat.V2.Service.Channel.MessageResource.Read(GlobalVariables.pathServiceSid, GlobalVariables.pathChannelSid);
                Message message = new Message();
                List<Message> listMessage = new List<Message>();
                foreach (var item in mess)
                {
                    message = new Message();
                    message.sid = String.IsNullOrEmpty(item.Sid) ? "" : item.Sid.ToString();
                    message.account_sid = String.IsNullOrEmpty(item.AccountSid) ? "" : item.AccountSid.ToString();
                    message.service_sid = String.IsNullOrEmpty(item.ServiceSid) ? "" : item.ServiceSid.ToString();
                    message.channel_sid = String.IsNullOrEmpty(item.ChannelSid) ? "" : item.ChannelSid.ToString();
                    message.body = String.IsNullOrEmpty(item.Body) ? "" : item.Body.ToString();
                    message.from = String.IsNullOrEmpty(item.From) ? "" : item.From.ToString();
                    listMessage.Add(message);
                }
                MessageMember messageMember = new MessageMember();
                messageMember.ListMember = listMember;
                messageMember.ListMessage = listMessage;
                messageMember.Nickname = GlobalVariables.GetUserName;

                return View(messageMember);
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
            
        }
        //
        [HttpPost]
        public ActionResult SendMessage(FormCollection collection)
        {
            string mensaje = Convert.ToString(collection["mensaje"]);
            string from = GlobalVariables.GetUserName;
            TwilioClient.Init(GlobalVariables.accountSid, GlobalVariables.authToken);

            var message = MessageResource.Create(
                body: mensaje,
                from: from,
                pathServiceSid: GlobalVariables.pathServiceSid,
                pathChannelSid: GlobalVariables.pathChannelSid
            );
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
    }
}

TwilioChat/TwilioChat/Views/Chat/ChatRoom.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    html, body {
        height: 100%;
        width: 100%;
        padding: 0;
        margin: 0;
        background-image: none;
        background-color: white;
    }

    .detailBox {
        width: 100%;
        border: 1px solid #bbb;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }

    .titleBox {
        background-color: #0e0d0d;
        padding: 10px;
    }

        .titleBox label {
            color: white;
            margin: 0;
            display: inline-block;
        }

    .commentBox {
        padding: 10px;
        border-top: 1px dotted #bbb;
    }

        .commentBox .form-group:first-child, .actionBox .form-group:first-child {
            width: 80%;
        }

        .commentBox .form-group:nth-child(2), .actionBox .form-group:nth-child(2) {
            width: 18%;
        }

    .actionBox .form-group * {
        width: 100%;
    }

    .taskDescription {
        margin-top: 10px 0;
    }

    .commentList {
        padding: 0;
        list-style: none;
        max-height: 200px;
        overflow: auto;
    }

        .commentList li {
            margin: 0;
            margin-top: 10px;
        }

            .commentList li > div {
                display: table-cell;
            }

    .commentText p {
        margin: 0;
    }

    .sub-text {
        color: #aaa;
        font-family: verdana;
        font-size: 11px;
    }

    .actionBox {
        border-top: 1px dotted #bbb;
        padding: 10px;
    }

    input, select, textarea {
        max-width: none;
    }

    .box {
        display: flex;
        flex-wrap: wrap;
    }
</style>

<br />
<h2>Chat Room</h2>

<br />
<div class="row" style="width:100%;">
    <div class="col-3">
        <div class="card" style="width: 100%;">
            <div class="card-body">
                <h5 class="card-title">Members connected</h5>
            </div>

            <ul class="list-group list-group-flush">
                @foreach (var member in Model.ListMember)
                {
                    <li class="list-group-item">@member.identity</li>
                }
            </ul>
        </div>
    </div>
    <div class="col-9" style="width: 100%;">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Chat</h5>
            </div>
            <div class="actionBox">
                <ul class="commentList">
                    @foreach (var message in Model.ListMessage)
                    {
                        <li>
                            <div class="commentText">
                                <p class="">@message.body</p> <span class="date sub-text">@message.from</span>
                            </div>
                        </li>
                    }
                </ul>
                @using (Html.BeginForm("SendMessage", "Chat",  FormMethod.Post))
                {
                    <div class="form-group" style="padding-right:0px;">
                        <input type="text" id="mensaje" name="mensaje" class="form-control" placeholder="Your message" />
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary right" value="Send" />

                    </div>
                }
            </div>
        </div>
    </div>
</div>

TwilioChat/TwilioChat/Views/Chat/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    html, body {
        height: 100%;
        width: 100%;
        padding: 0;
        margin: 0;
        background-image: none;
        background-color: white;
    }

    .detailBox {
        width: 100%;
        border: 1px solid #bbb;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }

    .titleBox {
        background-color: #0e0d0d;
        padding: 10px;
    }

        .titleBox label {
            color: white;
            margin: 0;
            display: inline-block;
        }

    .commentBox {
        padding: 10px;
        border-top: 1px dotted #bbb;
    }

        .commentBox .form-group:first-child, .actionBox .form-group:first-child {
            width: 80%;
        }

        .commentBox .form-group:nth-child(2), .actionBox .form-group:nth-child(2) {
            width: 18%;
        }

    .actionBox .form-group * {
        width: 100%;
    }

    .taskDescription {
        margin-top: 10px 0;
    }

    .commentList {
        padding: 0;
        list-style: none;
        max-height: 200px;
        overflow: auto;
    }

        .commentList li {
            margin: 0;
            margin-top: 10px;
        }

            .commentList li > div {
                display: table-cell;
            }

    .commentText p {
        margin: 0;
    }

    .sub-text {
        color: #aaa;
        font-family: verdana;
        font-size: 11px;
    }

    .actionBox {
        border-top: 1px dotted #bbb;
        padding: 10px;
    }

    input, select, textarea {
        max-width: none;
    }

    .box {
        display: flex;
        flex-wrap: wrap;
    }
</style>

<br />
@using (Html.BeginForm("ChatRoom", "Chat", FormMethod.Post))
{
    <div class="col-8">
        <div class="card" style="width: 100%;">
            <div class="card-header bg-dark text-light">JOIN</div>
            <div class="row" style="width:100%;">
                <div class="col-5">
                    <div class="card-body">

                        <div class="form-group">
                            <label for="nickname">NickName</label>
                            <input type="text" class="form-control" id="nickname" name="nickname" aria-describedby="nickname" placeholder="Enter your nickname">
                        </div>
                       
                    </div>
                </div>
                <div class="col-7">
                    <div class="card-body">
                        <div class="form-group">
                            <label>Select Channel</label>
                            <br />
                            @foreach (var channel in Model)
                            {
                                <input type="radio" name="radioChannel" value="@channel.sid">@channel.friendly_name<br>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <input type="submit" class="btn float-left btn-primary" value="Join" />
            </div>
        </div>
    </div>
}